In [ ]:
#get data from website terus without uploading manually first

!wget -O teleCust1000t.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DA0101EN/auto.csv

--2024-07-18 02:06:47--  https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DA0101EN/auto.csv
Resolving s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)... 67.228.254.196
Connecting to s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)|67.228.254.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24916 (24K) [text/csv]
Saving to: ‘teleCust1000t.csv’

teleCust1000t.csv   100%[===================>]  24.33K  --.-KB/s    in 0.002s

2024-07-18 02:06:48 (15.2 MB/s) - ‘teleCust1000t.csv’ saved [24916/24916]

In [ ]:
import pandas as pd

mydata1 = pd.read_csv('/content/teleCust1000t.csv')

mydata1.head(10)

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
5,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
6,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
7,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
8,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?
9,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430

In [ ]:
mydata.columns  #check the name of columns sebab data takda header

Index(['3', '?', 'alfa-romero', 'gas', 'std', 'two', 'convertible', 'rwd',
       'front', '88.6', '168.8', '64.1', '48.8', '2548', 'dohc', 'four', '130',
       'mpfi', '3.47', '2.68', '9.0', '111', '5000', '21', '27', '13495'],
      dtype='object')

In [ ]:
mydata.info()   #another solution to check the column names

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   3            204 non-null    int64
 1   ?            204 non-null    object
 2   alfa-romero  204 non-null    object
 3   gas          204 non-null    object
 4   std          204 non-null    object
 5   two          204 non-null    object
 6   convertible  204 non-null    object
 7   rwd          204 non-null    object
 8   front        204 non-null    object
 9   88.6         204 non-null    float64
 10  168.8        204 non-null    float64
 11  64.1         204 non-null    float64
 12  48.8         204 non-null    float64
 13  2548         204 non-null    int64
 14  dohc         204 non-null    object
 15  four         204 non-null    object
 16  130          204 non-null    int64
 17  mpfi         204 non-null    object
 18  3.47         204 non-null    object
 19  2.68         204 non-null    object
 20  9.0          204 non-null    float64
 21  111          204 non-null    object
 22  5000         204 non-null    object
 23  21           204 non-null    int64
 24  27           204 non-null    int64
 25  13495        204 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.6+ KB

In [ ]:
import pandas as pd   #letak header = none sebab taknak ambil first row as header

mydata = pd.read_csv('/content/teleCust1000t.csv', header = None)

mydata.head(10)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?

In [ ]:
mydata.columns

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25],
      dtype='int64')

In [ ]:
#replacing mydata.columns tu since tadi dia index, now replace with the header which kita name as name_col

name_col = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

mydata1.columns = name_col

mydata1.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [ ]:
mydata1.shape

(204, 26)

In [ ]:
mydata.shape

(205, 26)

In [ ]:
mydata.info()   #205 non-null. means 205 rows without missing value

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

**Missing Value**

In [ ]:
mydata.describe(include='all')  # '?' kira as missing value. sini display ada 3 dots. ada columns hidden

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
count,205.000000,205,205,205,205,205,205,205,205,205.000000,...,205.000000,205,205,205,205.000000,205,205,205.000000,205.000000,205
unique,NaN,52,22,2,2,3,5,3,2,NaN,...,NaN,8,39,37,NaN,60,24,NaN,NaN,187
top,NaN,?,toyota,gas,std,four,sedan,fwd,front,NaN,...,NaN,mpfi,3.62,3.40,NaN,68,5500,NaN,NaN,?
freq,NaN,41,32,185,168,114,96,120,202,NaN,...,NaN,94,23,20,NaN,19,37,NaN,NaN,4
mean,0.834146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.756585,...,126.907317,NaN,NaN,NaN,10.142537,NaN,NaN,25.219512,30.751220,NaN
std,1.245307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.021776,...,41.642693,NaN,NaN,NaN,3.972040,NaN,NaN,6.542142,6.886443,NaN
min,-2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.600000,...,61.000000,NaN,NaN,NaN,7.000000,NaN,NaN,13.000000,16.000000,NaN
25%,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.500000,...,97.000000,NaN,NaN,NaN,8.600000,NaN,NaN,19.000000,25.000000,NaN
50%,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.000000,...,120.000000,NaN,NaN,NaN,9.000000,NaN,NaN,24.000000,30.000000,NaN
75%,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.400000,...,141.000000,NaN,NaN,NaN,9.400000,NaN,NaN,30.000000,34.000000,NaN
max,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.900000,...,326.000000,NaN,NaN,NaN,23.000000,NaN,NaN,49.000000,54.000000,NaN

In [ ]:
#displaying all of the columns

pd.set_option('display.max_columns', None)

mydata.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,53.1,2507,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,192.7,71.4,55.7,2844,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,five,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,52.0,3053,ohc,five,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?

In [ ]:
mydata.isnull()   #nak tengok missing data. tapi susah nak tengok satu satu

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
203,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
204,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
mydata.isnull().sum() #calculate how many missing values in the columns. but only works if dia NaN by numpy. kalau tak, tak jumpa
# now the '?' tadi dia take as string. so dia tak kira missing value

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [ ]:
# replace '?' by NaN numpy   #now dah banyak dah missing value

import numpy as np

mydata.replace('?', np.nan, inplace = True)

mydata.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [ ]:
mydata.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [ ]:
mydata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       203 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               201 non-null    object
 19  stroke             201 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    object
 22  peak-rpm           203 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

**Columns with missing values:**

<ol>
    <li>"normalized-losses": 41 missing data</li>
    <li>"num-of-doors": 2 missing data</li>
    <li>"bore": 4 missing data</li>
    <li>"stroke" : 4 missing data</li>
    <li>"horsepower": 2 missing data</li>
    <li>"peak-rpm": 2 missing data</li>
    <li>"price": 4 missing data</li>
</ol>

In [ ]:
#set variable untuk each missing value of each columns dulu. now error sebab normalized-losses tu object

mean_norm = mydata['normalized-losses'].mean()

mean_norm

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
#safer to convert to float instead integer sebab kalau dia asal float, dia akan loss decimal points kat belakang.
#tapi kalau dia float asal integer, dapat no bulat and decimal points .0 je

mean_norm = mydata['normalized-losses'].astype('float').mean()

mean_norm

122.0

In [ ]:
#replacing the NaN in the normalized-losses column je

mydata['normalized-losses'].replace(np.nan, mean_norm, inplace = True)

mydata.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [ ]:
mydata.describe(include='all')  #dekat top tu kita tau dah which one is more frequent

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
count,205.000000,205.0,205,205,205,203,205,205,205,205.000000,205.000000,205.000000,205.000000,205.000000,205,205,205.000000,205,201,201,205.000000,203,203,205.000000,205.000000,201
unique,NaN,52.0,22,2,2,2,5,3,2,NaN,NaN,NaN,NaN,NaN,7,7,NaN,8,38,36,NaN,59,23,NaN,NaN,186
top,NaN,122.0,toyota,gas,std,four,sedan,fwd,front,NaN,NaN,NaN,NaN,NaN,ohc,four,NaN,mpfi,3.62,3.40,NaN,68,5500,NaN,NaN,8921
freq,NaN,41.0,32,185,168,114,96,120,202,NaN,NaN,NaN,NaN,NaN,148,159,NaN,94,23,20,NaN,19,37,NaN,NaN,2
mean,0.834146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.756585,174.049268,65.907805,53.724878,2555.565854,NaN,NaN,126.907317,NaN,NaN,NaN,10.142537,NaN,NaN,25.219512,30.751220,NaN
std,1.245307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.021776,12.337289,2.145204,2.443522,520.680204,NaN,NaN,41.642693,NaN,NaN,NaN,3.972040,NaN,NaN,6.542142,6.886443,NaN
min,-2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.600000,141.100000,60.300000,47.800000,1488.000000,NaN,NaN,61.000000,NaN,NaN,NaN,7.000000,NaN,NaN,13.000000,16.000000,NaN
25%,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.500000,166.300000,64.100000,52.000000,2145.000000,NaN,NaN,97.000000,NaN,NaN,NaN,8.600000,NaN,NaN,19.000000,25.000000,NaN
50%,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.000000,173.200000,65.500000,54.100000,2414.000000,NaN,NaN,120.000000,NaN,NaN,NaN,9.000000,NaN,NaN,24.000000,30.000000,NaN
75%,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.400000,183.100000,66.900000,55.500000,2935.000000,NaN,NaN,141.000000,NaN,NaN,NaN,9.400000,NaN,NaN,30.000000,34.000000,NaN
max,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.900000,208.100000,72.300000,59.800000,4066.000000,NaN,NaN,326.000000,NaN,NaN,NaN,23.000000,NaN,NaN,49.000000,54.000000,NaN

In [ ]:
mydata['num-of-doors'].value_counts()  #another approach to find the frequent value

num-of-doors
four    114
two      89
Name: count, dtype: int64

In [ ]:
mydata['num-of-doors'].value_counts().idxmax()  #ni dia bagi terus direct result mana most frequent

'four'

In [ ]:
#boleh je replace 'four'. ni kalau put formula tadi, dapat 'four' juga.

mydata['num-of-doors'].replace(np.nan, mydata['num-of-doors'].value_counts().idxmax(), inplace = True)

mydata.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [ ]:
mean_bore = mydata['bore'].astype('float').mean()

mean_bore

3.3297512437810943

In [ ]:
mydata['bore'].replace(np.nan, mean_bore, inplace = True)

mydata.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [ ]:
mean_stroke = mydata['stroke'].astype('float').mean()
mean_horse = mydata['horsepower'].astype('float').mean()
mean_peak = mydata['peak-rpm'].astype('float').mean()

mydata['stroke'].replace(np.nan, mean_stroke, inplace = True)
mydata['horsepower'].replace(np.nan, mean_horse, inplace = True)
mydata['peak-rpm'].replace(np.nan, mean_peak, inplace = True)
mydata.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [ ]:
#for price you can either drop the NaN or replace. tapi this one kita drop because kita nak predict the car price. so its okay

mydata.dropna(subset = ['price'], axis = 0, inplace = True)

mydata.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [ ]:
mydata.shape  #now dia 201 sebab tadi dah drop 4 rows of missing 'price'.

(201, 26)

#**Data Formatting**

In [ ]:
mydata.dtypes    #missing values gone. now working on making it all in correct data type

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [ ]:
#instead of tukar 1 by 1, boleh tukar semua serentak. bore, stroke, horsepower, etc... tapi tkar banyak kena letak 2 square brackets [[ABC]]

mydata['normalized-losses'] = mydata['normalized-losses'].astype('float')
mydata[['bore', 'stroke', 'horsepower', 'peak-rpm', 'price']] = mydata[['bore', 'stroke', 'horsepower', 'peak-rpm', 'price']].astype('float')

mydata.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                float64
dtype: object

In [ ]:
mydata.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [ ]:
#converting city mpg and highway mpg to L/km
#ni dia akan add new column which is city-L/100KM and highway tu

mydata['city_L/100KM'] = 235/mydata['city-mpg']
mydata['highway_L/100KM'] = 235/mydata['highway-mpg']

mydata.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city_L/100KM,highway_L/100KM
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,11.190476,8.703704
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,11.190476,8.703704
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,12.368421,9.038462
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0,9.791667,7.833333
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0,13.055556,10.681818

In [ ]:
#drop punya function ni akan delete whatever we put in the brackets.

mydata.drop('city-mpg', axis = 1, inplace = True)

mydata.drop('highway-mpg', axis = 1, inplace = True)

mydata.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,price,city_L/100KM,highway_L/100KM
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,13495.0,11.190476,8.703704
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,16500.0,11.190476,8.703704
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,16500.0,12.368421,9.038462
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,13950.0,9.791667,7.833333
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,17450.0,13.055556,10.681818

![image.png]()

#**Data Normalization**

* Simple Feature Scalling
* Min - max
* Z - Score

In [ ]:
#simple feature scalling

mydata['width'].head()

0    64.1
1    64.1
2    65.5
3    66.2
4    66.4
Name: width, dtype: float64

In [ ]:
mydata[['width', 'length', 'height']].head()

   width  length  height
0   64.1   168.8    48.8
1   64.1   168.8    48.8
2   65.5   171.2    52.4
3   66.2   176.6    54.3
4   66.4   176.6    54.3

In [ ]:
#simple feature scalling = width / max width
mydata['width'] = mydata['width']/mydata['width'].max()
mydata[['width', 'length', 'height']].head()

      width  length  height
0  0.890278   168.8    48.8
1  0.890278   168.8    48.8
2  0.909722   171.2    52.4
3  0.919444   176.6    54.3
4  0.922222   176.6    54.3

In [ ]:
mydata['width'].describe()

count    201.000000
mean       0.915126
std        0.029187
min        0.837500
25%        0.890278
50%        0.909722
75%        0.925000
max        1.000000
Name: width, dtype: float64

In [ ]:
# min-max = (length - min length) / (max length - min length)

mydata['length'] = (mydata['length']-mydata['length'].min())/(mydata['length'].max()-mydata['length'].min())

mydata[['width', 'length', 'height']].head()

      width    length  height
0  0.890278  0.413433    48.8
1  0.890278  0.413433    48.8
2  0.909722  0.449254    52.4
3  0.919444  0.529851    54.3
4  0.922222  0.529851    54.3

In [ ]:
mydata['length'].describe()

count    201.000000
mean       0.494045
std        0.183913
min        0.000000
25%        0.383582
50%        0.479104
75%        0.632836
max        1.000000
Name: length, dtype: float64

In [ ]:
# Z-score = height - height mean / height standard deviation

mydata['height'] = (mydata['height']-mydata['height'].mean())/mydata['height'].std()

mydata[['width', 'length', 'height']].describe()

            width      length        height
count  201.000000  201.000000  2.010000e+02
mean     0.915126    0.494045  7.070077e-17
std      0.029187    0.183913  1.000000e+00
min      0.837500    0.000000 -2.437541e+00
25%      0.890278    0.383582 -7.217300e-01
50%      0.909722    0.479104  1.361755e-01
75%      0.925000    0.632836  7.081124e-01
max      1.000000    1.000000  2.464776e+00

if you are using one method, all standardize to one method. if not semua akan ada slightly different value. but recommended to use the same method for all. normally people use **z score**.

#**Converting categorical to numerical**

* one hot-encoding
* encoder
* other

In [ ]:
mydata.describe(include='all')

#to convert, usually we look at the ones with low category which is Top = 2 and below senang to work on

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,price,city_L/100KM,highway_L/100KM
count,201.000000,201.00000,201,201,201,201,201,201,201,201.000000,201.000000,201.000000,2.010000e+02,201.000000,201,201,201.000000,201,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000
unique,NaN,NaN,22,2,2,2,5,3,2,NaN,NaN,NaN,NaN,NaN,6,7,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,toyota,gas,std,four,sedan,fwd,front,NaN,NaN,NaN,NaN,NaN,ohc,four,NaN,mpfi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,32,181,165,115,94,118,198,NaN,NaN,NaN,NaN,NaN,145,157,NaN,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,0.840796,122.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.797015,0.494045,0.915126,7.070077e-17,2555.666667,NaN,NaN,126.875622,NaN,3.330692,3.256874,10.164279,103.405534,5117.665368,13207.129353,9.944145,8.044957
std,1.254802,31.99625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.066366,0.183913,0.029187,1.000000e+00,517.296727,NaN,NaN,41.546834,NaN,0.268072,0.316048,4.004965,37.365700,478.113805,7947.066342,2.534599,1.840739
min,-2.000000,65.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.600000,0.000000,0.837500,-2.437541e+00,1488.000000,NaN,NaN,61.000000,NaN,2.540000,2.070000,7.000000,48.000000,4150.000000,5118.000000,4.795918,4.351852
25%,0.000000,101.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.500000,0.383582,0.890278,-7.217300e-01,2169.000000,NaN,NaN,98.000000,NaN,3.150000,3.110000,8.600000,70.000000,4800.000000,7775.000000,7.833333,6.911765
50%,1.000000,122.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.000000,0.479104,0.909722,1.361755e-01,2414.000000,NaN,NaN,120.000000,NaN,3.310000,3.290000,9.000000,95.000000,5125.369458,10295.000000,9.791667,7.833333
75%,2.000000,137.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.400000,0.632836,0.925000,7.081124e-01,2926.000000,NaN,NaN,141.000000,NaN,3.580000,3.410000,9.400000,116.000000,5500.000000,16500.000000,12.368421,9.400000
max,3.000000,256.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.900000,1.000000,1.000000,2.464776e+00,4066.000000,NaN,NaN,326.000000,NaN,3.940000,4.170000,23.000000,262.000000,6600.000000,45400.000000,18.076923,14.687500

In [ ]:
mydata[['num-of-doors', 'num-of-cylinders']].head(20)

   num-of-doors num-of-cylinders
0           two             four
1           two             four
2           two              six
3          four             four
4          four             five
5           two             five
6          four             five
7          four             five
8          four             five
10          two             four
11         four             four
12          two              six
13         four              six
14         four              six
15         four              six
16          two              six
17         four              six
18          two            three
19          two             four
20         four             four

In [ ]:
mydata['num-of-doors'].value_counts() #kita change 'four' as a string to number '4'

num-of-doors
four    115
two      86
Name: count, dtype: int64

In [ ]:
#replace je cam biasa

mydata['num-of-doors'].replace('four', 4, inplace=True)
mydata['num-of-doors'].replace('two', 2, inplace=True)

mydata[['num-of-doors', 'num-of-cylinders']].head(20)

    num-of-doors num-of-cylinders
0              2             four
1              2             four
2              2              six
3              4             four
4              4             five
5              2             five
6              4             five
7              4             five
8              4             five
10             2             four
11             4             four
12             2              six
13             4              six
14             4              six
15             4              six
16             2              six
17             4              six
18             2            three
19             2             four
20             4             four

In [ ]:
mydata['num-of-cylinders'].value_counts()

num-of-cylinders
four      157
six        24
five       10
two         4
eight       4
three       1
twelve      1
Name: count, dtype: int64

In [ ]:
mydata['num-of-cylinders'].replace('four', 4, inplace=True)
mydata['num-of-cylinders'].replace('six', 6, inplace=True)
mydata['num-of-cylinders'].replace('five', 5, inplace=True)
mydata['num-of-cylinders'].replace('two', 2, inplace=True)
mydata['num-of-cylinders'].replace('eight', 8, inplace=True)
mydata['num-of-cylinders'].replace('three', 3, inplace=True)
mydata['num-of-cylinders'].replace('twelve', 12, inplace=True)

mydata[['num-of-doors', 'num-of-cylinders']].head(20)

    num-of-doors  num-of-cylinders
0              2                 4
1              2                 4
2              2                 6
3              4                 4
4              4                 5
5              2                 5
6              4                 5
7              4                 5
8              4                 5
10             2                 4
11             4                 4
12             2                 6
13             4                 6
14             4                 6
15             4                 6
16             2                 6
17             4                 6
18             2                 3
19             2                 4
20             4                 4

In [ ]:
#one hot-encoding

conv_fuel = pd.get_dummies(mydata['fuel-type'],dtype=int)
conv_fuel.head()

   diesel  gas
0       0    1
1       0    1
2       0    1
3       0    1
4       0    1

In [ ]:
mydata_new = pd.concat([mydata, conv_fuel],axis=1)
mydata_new.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,price,city_L/100KM,highway_L/100KM,diesel,gas
0,3,122.0,alfa-romero,gas,std,2,convertible,rwd,front,88.6,0.413433,0.890278,-2.029015,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111.0,5000.0,13495.0,11.190476,8.703704,0,1
1,3,122.0,alfa-romero,gas,std,2,convertible,rwd,front,88.6,0.413433,0.890278,-2.029015,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111.0,5000.0,16500.0,11.190476,8.703704,0,1
2,1,122.0,alfa-romero,gas,std,2,hatchback,rwd,front,94.5,0.449254,0.909722,-0.558319,2823,ohcv,6,152,mpfi,2.68,3.47,9.0,154.0,5000.0,16500.0,12.368421,9.038462,0,1
3,2,164.0,audi,gas,std,4,sedan,fwd,front,99.8,0.529851,0.919444,0.217881,2337,ohc,4,109,mpfi,3.19,3.40,10.0,102.0,5500.0,13950.0,9.791667,7.833333,0,1
4,2,164.0,audi,gas,std,4,sedan,4wd,front,99.4,0.529851,0.922222,0.217881,2824,ohc,5,136,mpfi,3.19,3.40,8.0,115.0,5500.0,17450.0,13.055556,10.681818,0,1

In [ ]:
mydata_new.shape

(201, 28)

In [ ]:
conv_aspi = pd.get_dummies(mydata['aspiration'],dtype=int)
conv_aspi.head()

   std  turbo
0    1      0
1    1      0
2    1      0
3    1      0
4    1      0

In [ ]:
mydata_new1 = pd.concat([mydata_new, conv_aspi],axis=1)
mydata_new1.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,price,city_L/100KM,highway_L/100KM,diesel,gas,std,turbo
0,3,122.0,alfa-romero,gas,std,2,convertible,rwd,front,88.6,0.413433,0.890278,-2.029015,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111.0,5000.0,13495.0,11.190476,8.703704,0,1,1,0
1,3,122.0,alfa-romero,gas,std,2,convertible,rwd,front,88.6,0.413433,0.890278,-2.029015,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111.0,5000.0,16500.0,11.190476,8.703704,0,1,1,0
2,1,122.0,alfa-romero,gas,std,2,hatchback,rwd,front,94.5,0.449254,0.909722,-0.558319,2823,ohcv,6,152,mpfi,2.68,3.47,9.0,154.0,5000.0,16500.0,12.368421,9.038462,0,1,1,0
3,2,164.0,audi,gas,std,4,sedan,fwd,front,99.8,0.529851,0.919444,0.217881,2337,ohc,4,109,mpfi,3.19,3.40,10.0,102.0,5500.0,13950.0,9.791667,7.833333,0,1,1,0
4,2,164.0,audi,gas,std,4,sedan,4wd,front,99.4,0.529851,0.922222,0.217881,2824,ohc,5,136,mpfi,3.19,3.40,8.0,115.0,5500.0,17450.0,13.055556,10.681818,0,1,1,0

#**Data Binning**

In [ ]:
mydata['price'].describe()   #to understand the data better

count      201.000000
mean     13207.129353
std       7947.066342
min       5118.000000
25%       7775.000000
50%      10295.000000
75%      16500.000000
max      45400.000000
Name: price, dtype: float64

In [ ]:
#ni nak put dia in category.

price_bins = np.linspace(mydata_new1['price'].min(),mydata_new1['price'].max(),num=4)
print (price_bins)

price_groups=['Low Price', 'Mid Price', 'High Price']  #ni kita just put nama category je

mydata_new1['price_bins'] = pd.cut(mydata_new1['price'],bins=price_bins,labels=price_groups,include_lowest=True)
#guna ni untuk link kan category and numbers tu
#include_lowest tu to avoid ambil null value

mydata_new1[['price', 'price_bins']].head(10)

[ 5118.         18545.33333333 31972.66666667 45400.        ]

      price price_bins
0   13495.0  Low Price
1   16500.0  Low Price
2   16500.0  Low Price
3   13950.0  Low Price
4   17450.0  Low Price
5   15250.0  Low Price
6   17710.0  Low Price
7   18920.0  Mid Price
8   23875.0  Mid Price
10  16430.0  Low Price

In [ ]:
mydata_new1['price_bins'].value_counts() #check the categories. these are called imbalance classes (unequal amount in the categories)
#in ML nanti the machine will ambil low price model lebih banyak so jadi bias.

price_bins
Low Price     171
Mid Price      18
High Price     12
Name: count, dtype: int64

In [ ]:
mydata_new1.describe()  #takyah include all pun sebab binning only applicable to numerical data. so focus numerical je
#nak buat prediction, boleh try tengok features with difference gap min and max dia besar

,symboling,normalized-losses,num-of-doors,wheel-base,length,width,height,curb-weight,num-of-cylinders,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,price,city_L/100KM,highway_L/100KM,diesel,gas,std,turbo
count,201.000000,201.00000,201.000000,201.000000,201.000000,201.000000,2.010000e+02,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000
mean,0.840796,122.00000,3.144279,98.797015,0.494045,0.915126,7.070077e-17,2555.666667,4.363184,126.875622,3.330692,3.256874,10.164279,103.405534,5117.665368,13207.129353,9.944145,8.044957,0.099502,0.900498,0.820896,0.179104
std,1.254802,31.99625,0.992008,6.066366,0.183913,0.029187,1.000000e+00,517.296727,1.059452,41.546834,0.268072,0.316048,4.004965,37.365700,478.113805,7947.066342,2.534599,1.840739,0.300083,0.300083,0.384397,0.384397
min,-2.000000,65.00000,2.000000,86.600000,0.000000,0.837500,-2.437541e+00,1488.000000,2.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,5118.000000,4.795918,4.351852,0.000000,0.000000,0.000000,0.000000
25%,0.000000,101.00000,2.000000,94.500000,0.383582,0.890278,-7.217300e-01,2169.000000,4.000000,98.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,7775.000000,7.833333,6.911765,0.000000,1.000000,1.000000,0.000000
50%,1.000000,122.00000,4.000000,97.000000,0.479104,0.909722,1.361755e-01,2414.000000,4.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5125.369458,10295.000000,9.791667,7.833333,0.000000,1.000000,1.000000,0.000000
75%,2.000000,137.00000,4.000000,102.400000,0.632836,0.925000,7.081124e-01,2926.000000,4.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,16500.000000,12.368421,9.400000,0.000000,1.000000,1.000000,0.000000
max,3.000000,256.00000,4.000000,120.900000,1.000000,1.000000,2.464776e+00,4066.000000,12.000000,326.000000,3.940000,4.170000,23.000000,262.000000,6600.000000,45400.000000,18.076923,14.687500,1.000000,1.000000,1.000000,1.000000

In [ ]:
norm_bins = np.linspace(mydata_new1['normalized-losses'].min(),mydata_new1['normalized-losses'].max(),num=4)
print (norm_bins)

norm_groups=['Low', 'Mid', 'High']

mydata_new1['normalized_losses_bins'] = pd.cut(mydata_new1['normalized-losses'],bins=norm_bins,labels=norm_groups,include_lowest=True)

mydata_new1[['normalized-losses', 'normalized_losses_bins']].head(10)

[ 65.         128.66666667 192.33333333 256.        ]

    normalized-losses normalized_losses_bins
0               122.0                    Low
1               122.0                    Low
2               122.0                    Low
3               164.0                    Mid
4               164.0                    Mid
5               122.0                    Low
6               158.0                    Mid
7               122.0                    Low
8               158.0                    Mid
10              192.0                    Mid

In [ ]:
mydata_new1['normalized_losses_bins'].value_counts()

normalized_losses_bins
Low     140
Mid      55
High      6
Name: count, dtype: int64