### Data Science

**Big Data**

*Python*

[Click to view my profile](https://www.linkedin.com/in/syafiqah-syahirah-ayub/)

![sales-performance-dashboard.png]()

In [ ]:
a = 10
b = 20

c = a*b

print(c)

200

In [ ]:
print(c)

200

In [ ]:
c = a+b

print(c)

30

In [ ]:
import pandas as pd
df = pd.read_csv('NFLX.csv')
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-12-16,119.800003,123.000000,118.089996,122.639999,122.639999,13181000
1,2015-12-17,123.970001,126.349998,122.419998,122.510002,122.510002,17284900
2,2015-12-18,120.849998,122.190002,117.919998,118.019997,118.019997,17948100
3,2015-12-21,119.510002,119.589996,115.660004,116.629997,116.629997,11670000
4,2015-12-22,117.300003,117.430000,114.860001,116.239998,116.239998,9689000

In [ ]:
df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-12-16,119.800003,123.000000,118.089996,122.639999,122.639999,13181000
1,2015-12-17,123.970001,126.349998,122.419998,122.510002,122.510002,17284900
2,2015-12-18,120.849998,122.190002,117.919998,118.019997,118.019997,17948100
3,2015-12-21,119.510002,119.589996,115.660004,116.629997,116.629997,11670000
4,2015-12-22,117.300003,117.430000,114.860001,116.239998,116.239998,9689000
5,2015-12-23,116.910004,118.559998,115.779999,118.160004,118.160004,9324300
6,2015-12-24,118.220001,118.800003,117.300003,117.330002,117.330002,3531300
7,2015-12-28,117.260002,117.349998,113.849998,117.110001,117.110001,8424300
8,2015-12-29,118.190002,119.599998,116.919998,119.120003,119.120003,8159200
9,2015-12-30,118.949997,119.019997,116.430000,116.709999,116.709999,8149700

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
1002,2019-12-10,296.119995,298.940002,292.019989,293.119995,293.119995,10476100
1003,2019-12-11,294.489990,299.429993,294.200012,298.929993,298.929993,5589800
1004,2019-12-12,295.670013,299.170013,295.059998,298.440002,298.440002,4766600
1005,2019-12-13,298.500000,301.799988,297.250000,298.500000,298.500000,3879700
1006,2019-12-16,300.850006,305.709991,298.630005,304.209991,304.209991,4658900

In [ ]:
df.tail(10)

,Date,Open,High,Low,Close,Adj Close,Volume
997,2019-12-03,302.220001,307.359985,301.880005,306.160004,306.160004,4992800
998,2019-12-04,308.429993,308.429993,303.269989,304.320007,304.320007,3512100
999,2019-12-05,305.269989,306.480011,298.809998,302.859985,302.859985,4615500
1000,2019-12-06,304.700012,307.850006,302.600006,307.350006,307.350006,4457800
1001,2019-12-09,307.350006,311.489990,302.440002,302.500000,302.500000,5748400
1002,2019-12-10,296.119995,298.940002,292.019989,293.119995,293.119995,10476100
1003,2019-12-11,294.489990,299.429993,294.200012,298.929993,298.929993,5589800
1004,2019-12-12,295.670013,299.170013,295.059998,298.440002,298.440002,4766600
1005,2019-12-13,298.500000,301.799988,297.250000,298.500000,298.500000,3879700
1006,2019-12-16,300.850006,305.709991,298.630005,304.209991,304.209991,4658900

In [ ]:
df.shape

(1007, 7)

**Python Data Types**


* String
* Integer
* Float

In [ ]:
'Data Science'

8.8

2024

2024

In [ ]:
type ('Data Science')

str

In [ ]:
type (8.8)

float

In [ ]:
type(2024)

int

In [ ]:
int, float, complex

(int, float, complex)

In [ ]:
#complex

a = 3+5*b

a = 2

print (b)

1

In [ ]:
!python --version

Python 3.10.12

In [ ]:
type('2024')

str

In [ ]:
type("2025")

str

**Boolean Data Types**

* True
* False

In [ ]:
type(True)

bool

In [ ]:
type(False)

bool

In [ ]:
type (True)

bool

*Expressions, Variables, Conditions*

<ul>
    <li>subtraction: <b>-</b></li>
    <li>addition: <b>+</b></li>
    <li>division: <b>/</b></li>
    <li>floor division <b>//</b></li>
    <li>multiplication: <b>*</b></li>
    <li>modulus: <b>%</b></li>
    <li>exponent: <b>**</b></li>
</ul>

**Expressions**

In [ ]:
x = 8
z = 2

y = x / z

y

4.0

In [ ]:
type(y)

float

In [ ]:
y = x // z

In [ ]:
y

4

In [ ]:
type (y)

int

In [ ]:
d = 8
e = 3

f = d / e

f

2.6666666666666665

In [ ]:
f = d // e

In [ ]:
f

2

In [ ]:
b1 = 10%3
b2 = 10%2
b3 = 11%2
b4 = 11%3

print(b1)
print(b2)
print(b3)
print(b4)

1
0
1
2

In [ ]:
2**3

8

In [ ]:
8**4

4096

**Variables**

In [ ]:
type = 'big data'

In [ ]:
type(20)

TypeError: 'str' object is not callable

In [ ]:
machine learning = 'Data Science'

SyntaxError: invalid syntax (<ipython-input-36-90a1c9da181f>, line 1)

In [ ]:
machine_learning = 'Data Science'

In [ ]:
machine_learning

'Data Science'

In [ ]:
%whos

Variable           Type    Data/Info
------------------------------------
a                  int     2
abc                int     2025
b                  int     1
b1                 int     1
b2                 int     0
b3                 int     1
b4                 int     2
c                  int     2
d                  int     8
e                  int     3
f                  int     2
machine_learning   str     Data Science
type               str     big data
x                  int     8
y                  int     4
z                  int     2

In [ ]:
abc = 2025

**Condition**

<ul>
    <li>equal: <b>==</b></li>
    <li>not equal: <b>!=</b></li>
    <li>greater than: <b>></b></li>
    <li>less than: <b>&lt;</b></li>
    <li>greater than or equal to: <b>>=</b></li>
    <li>less than or equal to: <b>&lt;=</b></li>
</ul>

In [ ]:
year = 2024

year == 2024

True

In [ ]:
year != 2025

True

In [ ]:
year == 2026

False

**String Indexing**

In [ ]:
singer = 'Michael Jackson'

singer

'Michael Jackson'

In [ ]:
type(singer)

str

In [ ]:
print(singer)
print(singer[2])
print(singer[5])
print(singer[10])
print(singer[13])

Michael Jackson
c
e
c
o

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsIndex.png" width="600" align="center" />

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsNeg.png" width="600" align="center" />

In [ ]:
print(singer[-13])

print(singer[-10])

print(singer[-2])

c
e
o

In [ ]:
# print the last, second last, first and the second of any string

# first
print(anystring[0])
#second
print(anything[1])
#last
print(anything[-1])
#second last
print(anything[-2])

**Index Slicing**

print(anystring[index to start from : index to stop at])

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsIndex.png" width="600" align="center" />

In [ ]:
print (singer[0:6]) #tak ambil kira last index. so kena stop at 7

Michae

In [ ]:
print(singer [0:7])

Michael

In [ ]:
print(singer[:7])  #if tak letak dia assume ambil from beginning and stop at 7

Michael

In [ ]:
print(singer[7:])  #printing Jackson. ni ada space kat depan J

 Jackson

In [ ]:
print(singer[8:])  #now dia ambil exactly 'Jackson' je. without space

Jackson

In [ ]:
print(singer[8:-1])  #try ambil number yang -ve dari belakang. nak print Jackson

Jackso

In [ ]:
print(singer[-7:])

Jackson

In [ ]:
print(singer[8:15])

Jackson

In [ ]:
print(singer[:7:2])  #number 2 belakang means dia ambil index ke 2

Mcal

In [ ]:
print(singer[:7:3])  #number 3 means dia ambil yang ke 3

Mhl

**Concatenating String**

In [ ]:
str1 = 'Big'
str2 = 'Data'

str3 = str1 + str2

print(str3)

BigData

In [ ]:
str4 = str2 + str1

str4

'DataBig'

In [ ]:
str3 = str1 + ' ' + str2

str3

'Big Data'

In [ ]:
str5 = str1 + 2024   #ni error sebab 2024 takda ' ' so dia interger. integer takleh gabung string

str5

TypeError: can only concatenate str (not "int") to str

In [ ]:
str5 = str1 + '2024'

str5

'Big2024'

In [ ]:
str6 = '2024'   #ni dah convert string '2024' to integer

str6

'2024'

In [ ]:
type (str6)   #now dia masih string

str

In [ ]:
str7 = int(str6)   #dia gabung dengan integer

str7

2024

In [ ]:
type (str7)   #now jadi integer

int

In [ ]:
str8 = str1 + 2.2  #try gabung string dengan float. error sebab tak boleh gabung

TypeError: can only concatenate str (not "float") to str

In [ ]:
str9 = str(2.2)   #convert float to string

str9

'2.2'

In [ ]:
str8 = str1 + str9   #gabung strings

str8

'Big2.2'

In [ ]:
test1 = int(str(999))

type(test1)

int

In [ ]:
test2 = str(int(float(999)))

type(test2)

str

**Python Data Structure**

* List  []
* Tuple ()
* Set   {}
* Dictionary  {}

In [ ]:
l1 = [8.8, 'Data Science', 2024, 99, -20]

t1 = (8.8, 'Data Science', 2024, 99, -20)

s1 = {8.8, 'Data Science', 2024, 99, -20}

print(l1)
print(t1)
print(s1)

[8.8, 'Data Science', 2024, 99, -20]
(8.8, 'Data Science', 2024, 99, -20)
{99, 8.8, 2024, -20, 'Data Science'}

In [ ]:
type (l1)

list

In [ ]:
type (t1)

tuple

In [ ]:
type(s1)

set

**List**

In [ ]:
#index

print(l1[2])
print(l1[2:])

2024
[2024, 99, -20]

In [ ]:
#extend   -add items to the list. if you keep running this below, 55 dengan AI to akan keep on added. run again yang original then tambah sekali je

l1.extend([55,'AI'])

l1

[8.8, 'Data Science', 2024, 99, -20, 55, 'AI']

In [ ]:
#append    add in new list IN the original list

l1.append(['ML',999])

l1

[8.8, 'Data Science', 2024, 99, -20, 55, 'AI', ['ML', 999]]

In [ ]:
#nested list - ni boleh extract ['ML,999] as one item

print(l1[-1])

['ML', 999]

In [ ]:
print(l1[-1][-1])  #to extract only 999 dalam one item yang kita extract tadi

999

In [ ]:
l2 = [8.8, 'Data Science', 2024, 99, -20, 55, 'AI', ['ML',999, ['A','B','C']]]

#print the latter B and C

print(l2[-1][-1][-2:])

['B', 'C']

In [ ]:
#del   deleting items

del(l1[1])

l1

[8.8, -20, 55, 'AI', ['ML', 999]]

In [ ]:
l1 = [8.8, 99, -20, 55, 'AI', ['ML', 999]]

In [ ]:
l1.index('AI')

4

In [ ]:
#counting the freq of an item in a list

l3 = [20, 200, 99, 20, 'AI', 20, 'AI', 20]

#count

l3.count(20)

4

In [ ]:
l3.count('AI')

2

In [ ]:
l3.index('AI')

4

In [ ]:
l3

[20, 200, 99, 20, 20, 'AI', 20]

In [ ]:
#remove

l3.remove('AI')

l3

[20, 200, 99, 20, 20, 20]

In [ ]:
#insert

#list.insert(index, item)

l3.insert(4, 'AI')

l3

[20, 200, 99, 20, 'AI', 20, 20]

In [ ]:
#reverse  dia akan reverse the order of list cam transpose

l3.reverse()

l3

[20, 200, 99, 20, 'AI', 20, 20]

In [ ]:
#sort

l3.sort()

l3

TypeError: '<' not supported between instances of 'str' and 'int'

In [ ]:
l3.remove('AI')

l3

ValueError: list.remove(x): x not in list

In [ ]:
l3    #sini dah remove 'AI'

[20, 20, 99, 200, 20, 20]

In [ ]:
l3.sort()    #ni dia sort lowest to highest

l3

[20, 20, 20, 20, 99, 200]

In [ ]:
l3.reverse()    #ni kalau nak descending order

l3

[200, 99, 20, 20, 20, 20]

In [ ]:
#length

len(l3)

6

In [ ]:
l4 = [20, 0, -5, 13, -1, 7, 4, -3, 17, 9]

#sort l4 in ascending and decending
#print the highest value and lowest value

l4.sort()

l4

[-5, -3, -1, 0, 4, 7, 9, 13, 17, 20]

In [ ]:
l4.reverse()
l4

[20, 17, 13, 9, 7, 4, 0, -1, -3, -5]

In [ ]:
print('The highest value is: ',l4[0])
print('The lowest value is: ',l4[-1])

The highest value is:  20
The lowest value is:  -5

**Tuple**

### List
- *Mutable*: You can change the elements (add, remove, or modify) after the list is created.
- *Syntax*: Defined using square brackets [].
  python
  my_list = [1, 2, 3]
  
- *Performance*: Slightly slower due to the flexibility of mutability.
- *Use Case*: Best when you need a collection of items that may change over time.

### Tuple
- *Immutable*: Once created, you cannot change the elements (no adding, removing, or modifying).
- *Syntax*: Defined using parentheses ().
  python
  my_tuple = (1, 2, 3)
  
- *Performance*: Faster than lists due to immutability.
- *Use Case*: Best when you need a collection of items that should not change, ensuring data integrity.

### Key Differences
1. *Mutability*:
   - Lists: Mutable
   - Tuples: Immutable

2. *Syntax*:
   - Lists: []
   - Tuples: ()

3. *Performance*:
   - Lists: Slower due to overhead of mutable operations.
   - Tuples: Faster due to immutability.

4. *Use Cases*:
   - Lists: Collections of items that need to be changed or updated.
   - Tuples: Fixed collections of items that should not change after creation.

### Example
#### List
python
my_list = [1, 2, 3]
my_list.append(4)
print(my_list)  # Output: [1, 2, 3, 4]


#### Tuple
python
my_tuple = (1, 2, 3)
# my_tuple.append(4)  # This will raise an AttributeError
print(my_tuple)  # Output: (1, 2, 3)


### Summary
- Use *lists* when you need a dynamic collection that may change over time.
- Use *tuples* when you need a fixed collection of items that should remain constant.

In [ ]:
t1

(8.8, 'Data Science', 2024, 99, -20)

In [ ]:
print(t1[2])

2024

In [ ]:
#nested tuple = tuple inside a tuple

t2 = (8.8, 'Data Science', (2024, 99), -20)

print(t2[-2][-1])

99

In [ ]:
t3 = ('AI', 'Phyton')   #kan tuple tak boleh add in things. so kita insert tuple inside tuple. pastu nama baru

tnew = t2 + t3

tnew

(8.8, 'Data Science', (2024, 99), -20, 'AI', 'Phyton')

In [ ]:
t4 = (5, 88, -20, 99, 30, 8.8, 0, 5)  #sorted punya function tukar tuple jadi list. so kita boleh sort tuple

#sorted
sort_t4 = sorted(t4)

print(sort_t4)

[-20, 0, 5, 5, 8.8, 30, 88, 99]

In [ ]:
list_t4 = list(t4)    #ni sama juga boleh convert tuple jadi list

list_t4

[5, 88, -20, 99, 30, 8.8, 0, 5]

In [ ]:
tuple_list_t4 = tuple(list_t4)   #reverse back to tuple

tuple_list_t4

(5, 88, -20, 99, 30, 8.8, 0, 5)

In [ ]:
t5 = ('AI', 'Data', 2024, 'ML')

list_new_items = [888, 'Python', 'DL']

#create a new tuple of the above tuple and list   kalau run tuple, usually faster than list sebab tuple tak mutable (data cannot change)

list_t5 = list(t5)

In [ ]:
list_t5.extend(list_new_items)

list_t5

['AI', 'Data', 2024, 'ML', 888, 'Python', 'DL']

In [ ]:
new_tuple = tuple(list_t5)

new_tuple

('AI', 'Data', 2024, 'ML', 888, 'Python', 'DL')

**Set**

In [ ]:
s1 = {8.8, 'Data Science', 99, 2.2, 'Python'}

type (s1)

set

In [ ]:
print(s1)  #set - setting the items in ascending order. tak ambil duplicate items

{2.2, 99, 'Data Science', 'Python', 8.8}

In [ ]:
s1

{2.2, 8.8, 99, 'Data Science', 'Python'}

In [ ]:
s2 = {20, -10, 0, 5, 99, -10, 20, 2.2, 88} #set removed duplicates

print (s2)

{0, 2.2, 99, 20, 5, -10, 88}

In [ ]:
s2 #kalau 'PRINT' dia keluar ikut apa kita program. if call out je variable, dia akan ikut dia punya nature eg:ikut ascending order

{-10, 0, 2.2, 5, 20, 88, 99}

In [ ]:
s3 = {'data', 'ai', 'ML', 'python', 'big data'} #dia susun ikut alphabet. tapi ML capital letter, dia prioritize

s3

{'ML', 'ai', 'big data', 'data', 'python'}

In [ ]:
s4 = {'data', 'ai', 'ml', 'python', 'big data'}

s4

{'ai', 'big data', 'data', 'ml', 'python'}

In [ ]:
s5 = {'Data', 'ai', 'mL', 'Python', 'Big data'}

s5

{'Big data', 'Data', 'Python', 'ai', 'mL'}

In [ ]:
#add items in the set    #dia akan sort auto on its own way

s5.add('deep learning')

s5

{'Big data', 'Data', 'Python', 'ai', 'deep learning', 'mL'}

In [ ]:
s2

{-10, 0, 2.2, 5, 20, 88, 99}

In [ ]:
s2.add(10)

s2

{-10, 0, 2.2, 5, 10, 20, 88, 99}

In [ ]:
#remove items from set

s2.remove(88)

s2

{-10, 0, 2.2, 5, 10, 20, 99}

In [ ]:
#intersection

set_a = {1,3,5,7,8,9,10,11,12,13,14} #actual results
set_b = {1,2,3,4,5,6,7,8,9,10,11}  #predicted results

set_a.intersection(set_b)

{1, 3, 5, 7, 8, 9, 10, 11}

In [ ]:
#union     #remove duplicates

set_a.union(set_b)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14}

In [ ]:
list_a = [1,2,3,4,1,2,5]  #convert list to a set

set_list_a = set(list_a)

set_list_a

{1, 2, 3, 4, 5}

In [ ]:
#write a code to find the highest value in a list of numbers by using set only

list_b = [100, -99, 101, 88, 55.6, 0]

set_list_b = set(list_b)

set_list_b

print('The highest value is: ',max(set_list_b))
print('The lowest value is: ',min(set_list_b))

The highest value is:  101
The lowest value is:  -99

In [ ]:
#difference  #ada dalam set a tapi takda dalam set b. means model misprediction

set_a.difference(set_b)

{12, 13, 14}

In [ ]:
set_b.difference(set_a)  #ada dalam set b, takda dalam a. means incorrect prediction. takda dalam actual results

{2, 4, 6}

**Dictionary**

* Each item has a key and a value
* Key : value
* Dictionary: {key1:value1, key2:value2, .... keyn:valuen}

#####data to represent other data. eg: movie:category movie OR student names:marks

In [ ]:
d1 = {'AI':99, 8.8:['ML', 'DL'], (1,2,3):['Big Data']}

d1

{'AI': 99, 8.8: ['ML', 'DL'], (1, 2, 3): ['Big Data']}

In [ ]:
type (d1)

dict

In [ ]:
d1[(1,2,3)]     #the KEY is the index to represent the value. so if kita call (1,2,3) value dia ialah 'Big Data'

['Big Data']

In [ ]:
d1.keys()  #yang ni call keys of the dictionary.

dict_keys(['AI', 8.8, (1, 2, 3)])

In [ ]:
d1.values()  #ni dia call values je

dict_values([99, ['ML', 'DL'], ['Big Data']])

In [ ]:
d1

{'AI': 99, 8.8: ['ML', 'DL'], (1, 2, 3): ['Big Data']}

In [ ]:
d1['AI'] = -10  #use the KEY to update data. ni dia change the VALUE for 'AI'

d1

{'AI': -10, 8.8: ['ML', 'DL'], (1, 2, 3): ['Big Data']}

In [ ]:
d1  #guna d1.pop(1, 2, 3) to remove the whole key and value. ni sebab dah TER run previously making the whole set tadi dah remove so dia jadi error

{'AI': -10, 8.8: ['ML', 'DL']}

In [ ]:
d2 = {[1,2]:99, (100, 200):['obay']}

d2

TypeError: unhashable type: 'list'

In [ ]:
d3 = {(1,2):99, (100, 200):['obay']}

d3

{(1, 2): 99, (100, 200): ['obay']}

**If statement, elif statement, else**

In [ ]:
country = 'Malaysia'   #bila dah pakai if line bawah dia ada indentation means semua bawah block of code. to maintain specific task inside the block

if country == 'Malaysia':   #blank ni means if its TRUE, python will continue running the block of code
    print('Country is Malaysia')

Country is Malaysia

In [ ]:
country = 'Malaysia'

if country == 'Singapore':    #sini dia FALSE sebab bukan Malaysia, dia tak keluar result, tambah else means if country lain, dia akan print as ELSE punya command
  print('Country is Singapore')

elif country == 'Thailand':   #sini FALSE juga so dia still print as ELSE punya command
  print('Country is Thailand')

elif country != 'Singapore':   #True
  print('Country is unknown')

else:
  print('Country is not Malaysia')

Country is unknown

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/CondsTable.png" width="650" />

In [ ]:
country = 'Malaysia'
year = 2024

if country == 'Malaysia' and year == 2020:  #False
  print('Country is Malaysia and year is 2020')

In [ ]:
country = 'Malaysia'
year = 2024

if country == 'Malaysia' or year == 2020:  #False
  print('Country is Malaysia and year is 2020')

Country is Malaysia and year is 2020

In [ ]:
country = 'Malaysia'
year = 2024

if country == 'Malaysia' and year != 2020:  #False
  print('Country is Malaysia and year is 2020')

Country is Malaysia and year is 2020

In [ ]:
country = 'Malaysia'
year = 2024

if country == 'Malaysia' and year > 2020:  #False
  print('Country is Malaysia and year is 2020')

Country is Malaysia and year is 2020

In [ ]:
country = 'Malaysia'
year = 2024

if country == 'Malaysia' and year == 2020: #False
  print('Country is Malaysia and year is 2020')

elif country == 'Malaysia' and year > 2020: #True
  print('Country is Malaysia and year is earlier than 2020')

Country is Malaysia and year is earlier than 2020

In [ ]:
# write a code for finding the even and odd numbers

num = 10

if num % 2 == 0:
  print('Number is even')

else:
  print('Number is odd')

Number is even

In [ ]:
input_num = input('Enter a number')

input_num = int(input_num)

if input_num % 2 == 0:
  print('Number is even')

else:
  print('Number is odd')

Enter a number10
Number is even

In [ ]:
#nested if, elif, else statements    #if inside if

price = 1000
car = 'Proton'

if price > 500: #False
  if price == 700: #False
    print('The price is more than 700')

  else:
    if price == 100 or car == 'Proton':  #True
      print('Car is Proton')

    else:
      print('Price and Car are unknown')

Car is Proton

**Loops and While Loop**

##### dia akan keep on repeat or reiterate by itself

In [ ]:
list_num = [100, 200, 300, 400, 500]

print (list_num[0])
print (list_num[1])
print (list_num[2])
print (list_num[3])
print (list_num[4])

100
200
300
400
500

**For loop**

In [ ]:
list_num

[100, 200, 300, 400, 500]

In [ ]:
for i in list_num:   # 'i' tu counter dia. will auto run from the first and stop after the last one. the next command nak print ke multiply ke semua boleh. dia akan do for all the items in the list
  print(i)

100
200
300
400
500

In [ ]:
for num in range(1, 10):   #ni to count numbers. kita letak range je
  print(num)

1
2
3
4
5
6
7
8
9

In [ ]:
numbers = [1,2,3,4,5,6]

#write a code to print numbers below 5

for num in numbers:
  if num <5:
    print (num)

1
2
3
4

In [ ]:
numbers1 = [-1, 2, 1, 3, 5, 4, 0]

#write a code to print all the numbers below 5

for num in numbers1:
  if num <5:
    print (num)

-1
2
1
3
4
0

In [ ]:
d1 = {'AI': -10, 8.8: ['ML', 'DL']}

In [ ]:
for i in d1:   #ni auto dia bagi KEY by turutan
  print(i)

AI
8.8

In [ ]:
for i in d1.values():   #ni kita specifically ask for the VALUES for d1 ikut turutan
  print(i)

-10
['ML', 'DL']

In [ ]:
for i in d1.items():
  print(i)

('AI', -10)
(8.8, ['ML', 'DL'])

In [ ]:
#While Loop. less use than for loop. whatever used while loop can use for loop
#start dengan define counter dia i=?

numbers = [1,2,3,4,5,6]

#write a code to print numbers below 5 by using while loop

i = 0  #1 #2 #3 #4 #5
num = None #1 #2 #3 #4 #5

while (num!=5): #True #True #True #True #True #False
  num = numbers[i]
  i = i + 1
  print (num)

1
2
3
4
5

In [ ]:
numbers = [1,2,3,4,5,6]

#write a code to print numbers below 5 by using while loop.now dia nak bawah 5 so while (num!=5) tu tkar jadi 4, terus leave out 5

i = 0
num = None

while (num!=4):
  num = numbers[i]
  i = i + 1
  print (num)

1
2
3
4

In [ ]:
#write a code to print numbers below 4 by using while loop  #another example

numbers = [1,2,3,4,5,6]

i = 0  #i ni jadi index start dengan 0 sebab kan dia loop so next loop akan add 1
num = None

while (num!=3):
  num = numbers[i]
  i = i + 1
  print (num)

1
2
3

In [ ]:
#nested loops = loops inside loops

names = ['Mohammed', 'Noor', 'Chyrel']

for a in names:
  print (a)

  for b in (a):
    print (b)

  print ('')  #this is just to add the space in between mohammed and noor tu

Mohammed
M
o
h
a
m
m
e
d

Noor
N
o
o
r

Chyrel
C
h
y
r
e
l

In [ ]:
#write a code to print only even numbers in range of numbers 20

for i in range(21):
  if i % 2 == 0:
    print (i)

0
2
4
6
8
10
12
14
16
18
20

In [ ]:
#create of those even numbers in a list

list_i = list(i for i in range(21) if i %2 == 0)

(list_i)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
list_even = []
for i in range (21):
  if i % 2 == 0:
    list_even.append(i)
  print (list_even)

[0]
[0]
[0, 2]
[0, 2]
[0, 2, 4]
[0, 2, 4]
[0, 2, 4, 6]
[0, 2, 4, 6]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8, 10]
[0, 2, 4, 6, 8, 10]
[0, 2, 4, 6, 8, 10, 12]
[0, 2, 4, 6, 8, 10, 12]
[0, 2, 4, 6, 8, 10, 12, 14]
[0, 2, 4, 6, 8, 10, 12, 14]
[0, 2, 4, 6, 8, 10, 12, 14, 16]
[0, 2, 4, 6, 8, 10, 12, 14, 16]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
list_even = []
for i in range (21):
  if i % 2 == 0:
    list_even.append(i)
print (list_even)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

**Given a list of numbers, write a code to calculate the sum of even numbers in that list**

In [ ]:
print(sum(list_even))

110

In [ ]:
sum_even = 0

for i in range(10):
  if i % 2 == 0:
    sum_even = sum_even + i

print('The sum of all even numbers are:', sum_even)

The sum of all even numbers are: 20

In [ ]:
#Given a string, write a code to calculate the number of vowels (a,e,i,o,u) in the string. the string is: 'Hello World' #APPROACH 1

string = 'Hello World'

vowel_count = 0

for i in string:
  if i == 'a' or i == 'e' or i == 'i' or i == 'o' or i == 'u':
    vowel_count = vowel_count + 1

print('The number of vowels are:', vowel_count)

The number of vowels are: 3

In [ ]:
#Given a string, write a code to calculate the number of vowels (a,e,i,o,u) in the string. the string is: 'Hello World' #APPROACH 2

string = 'Artificial Intelligence'

count_vowel = 0

for vow in string.lower():   #lower akan lowercase kan semua letter. so dia count A and I. same goes for upper. will uppercase semua letter
  if vow in 'a,e,i,o,u':
    count_vowel += 1  #count_vowel = count_vowel + 1

print('The number of vowels are: ', count_vowel)

The number of vowels are:  10

*Function*

To define a function in Python, use the "def" keyword, followed by the function name, parentheses, and a colon. The body of the function is indented and contains the code to be executed when the function is called.

def funname(arguments):

In [ ]:
def first_fun():
  '''    #between the 3 dots opening and closing, python tak kira as coding
  This is a function
  '''
  print('This is my first function')

In [ ]:
first_fun()

This is my first function

In [ ]:
def sum_num(a,b):
  '''This function is about summing two numbers'''

  c = a + b
  print(c)

In [ ]:
sum_num(10,5)

15

In [ ]:
sum_num('Big', ' Data')

Big Data

In [ ]:
def sum_num(a,b):
  '''This function is about summing two numbers'''

  c = float(a) + float(b)
  print(c)

In [ ]:
sum_num('Big', ' Data')

ValueError: could not convert string to float: 'Big'

In [ ]:
def multi_num(a, b, c):
  d = a * b * c
  return(d)   #PRINT to display only to display. RETURN value can be used for later

In [ ]:
multi_num(10, 1, 2)

20

**Print vs Return**

To summarize, "print" is used to output values to the console for debugging or informational purposes, while "return" is used to send a value back from a function to the calling code. If you want to use the result of a function in other parts of your code, you need to use "return" to make that value available outside the function.



*print just shows the human user a string representing what is going on inside the computer. The computer cannot make use of that printing. return is how a function gives back a value. This value is often unseen by the human user, but it can be used by the computer in further functions.*

In [ ]:
#Write a function to find the even and odd numbers

def even_odd(num):
  if num % 2 == 0:
    print('Number is even')

  else:
    print('Number is odd')

In [ ]:
even_odd(158907)

Number is odd

In [ ]:
#write a function to find the highest value in a list of numbers without using other functions

list_num = [100, 0, 5, 200, -20, 8.8]

def max_num(list_num):
  max_num = 0

  for num in list_num:
    if num > max_num:
      max_num = num

  return max_num

In [ ]:
max_num(list_num)

200

In [ ]:
#write a function to find the highest value in a list of numbers without using other functions

list_num = [100, 0, 5, 200, -20, 8.8]

highest = list_num[0]    #ni dia letak the first index as the highest means 100 tu highest
lowest = list_num[0]

for i in list_num:
  if i > highest:       #ni condition dia if 0 > 100, dia false so dia stay. sampai 100 > 200 jadi false, dia ambil 200 as highest
    highest = i

  if i < lowest:
    lowest = i

print('The highest value in the list is: ', highest)
print('The lowest value in the list is: ', lowest)

The highest value in the list is:  200
The lowest value in the list is:  -20

In [ ]:
list_num = [100, 0, 5, 200, -20, 8.8]

lowest = list_num[0]

for i in list_num:
  if i < lowest:
    lowest = i

print('The lowest value in the list is: ', lowest)

The lowest value in the list is:  -20

In [ ]:
def high_low(list_num):

  highest = list_num[0]
  lowest = list_num[0]

  for i in list_num:
    if i > highest:
      highest = i

  for i in list_num:
    if i < lowest:
     lowest = i

  print('The highest value in the list is: ', highest)
  print('The lowest value in the list is: ', lowest)

In [ ]:
e%whos

Variable       Type        Data/Info
------------------------------------
a              str         Chyrel
b              str         l
count_vowel    int         10
d1             dict        n=2
even_odd       function    <function even_odd at 0x7ce850bb3e20>
first_fun      function    <function first_fun at 0x7ce850d0f9a0>
high_low       function    <function high_low at 0x7ce850d06320>
highest        int         200
i              float       8.8
list_even      list        n=11
list_i         list        n=11
list_num       list        n=6
lowest         int         -20
max_num        function    <function max_num at 0x7ce850bb2b90>
maxmin_num     function    <function maxmin_num at 0x7ce850d07010>
multi_num      function    <function multi_num at 0x7ce850bb0ca0>
multiply_num   function    <function multiply_num at 0x7ce850d0eef0>
names          list        n=3
num            int         3
numbers        list        n=6
numbers1       list        n=7
s1             str         Hello World
string         str         Artificial Intelligence
sum_even       int         20
sum_num        function    <function sum_num at 0x7ce850bb3520>
vow            str         e
vowel_count    int         3
vowels         str         e

In [ ]:
list_num_1 = [300, 111, 400, -2, 0, 55, 8.8, 99, 1.5, 44]

high_low(list_num_1)

The highest value in the list is:  400
The lowest value in the list is:  -2

Write a function to sum the even numbers in a list of numbers

In [ ]:
list_num = [100, 0, 5, 200, -20, 8.8]

def sum_even(list_num):
  sum_even = 0

  for i in list_num:
    if i % 2 == 0:
      sum_even = sum_even + i

  print('The total sum of even numbers are: ', sum_even)

In [ ]:
sum_even(list_num)

The total sum of even numbers are:  280

In [ ]:
sum_even(list_num_1)

The total sum of even numbers are:  742

In [ ]:
#Find the missing value in the list below
#sort the list. then check difference between the next value. if difference more than 1 means there's missing value

list_missing = [1, 4, 3, 2, 5, 8, 7]

def missing_value(list_missing):
  list_missing.sort()

  for i in range(1,7):
    if i != list_missing[i-1]:
      print('The missing value is: ', i)

In [ ]:
missing_value(list_missing)

The missing value is:  6

In [ ]:
#Find the missing value in the list below
#sort the list. then check difference between the next value. if difference more than 1 means there's missing value

list_missing = [1, 4, 3, 2, 5, 8, 7]

def missing_value(list_missing):
  list_missing.sort()

  for i in range(1,len(list_missing)):
    if list_missing[i] - list_missing[i-1] != 1:
      print('The missing value is: ', (list_missing[i] - 1))
  #return list_missing [i-1]

    else:
      print ('There is no missing value')
  #return None

In [ ]:
missing_value(list_missing)

The missing value is:  6

In [ ]:
# write a function to remove duplicates from a list of numbers  #APPROACH 1 convert to set and back to list

list_duplicate = [100, 20, -30, 100, 20, 0, -30]

def remove_duplicate(list_duplicate):
  list_duplicate = list(set(list_duplicate))
  return list_duplicate

In [ ]:
remove_duplicate(list_duplicate)

[0, -30, 100, 20]

In [ ]:
# write a function to remove duplicates from a list of numbers    #APPROACH 2 using append

list_duplicate = [100, 20, -30, 100, 20, 0, -30]

def remove_duplicates(input_list):

  result = [] # Step 1: Create an empty list named 'result' to store unique numbers.
  for num in input_list: # Step 2: Start iterating through each number ('num') in the 'input_list'.
    if num not in result: # Step 3: Check if the current number 'num' is NOT already in the 'result' list.
      result.append(num) # Step 4: If 'num' is not in 'result', it's unique, so append it to the 'result' list.
  return result # Step 5: After checking all numbers, return the 'result' list containing only unique numbers.

In [ ]:
remove_duplicates(list_duplicate)

[100, 20, -30, 0]

In [ ]:
# write a function to remove duplicates from a list of numbers  #APPROACH 3 using count and remove count more than 1

list_duplicate = [100, 20, -30, 100, 20, 0, -30]

counts = {}
for i in list_duplicate:
  if list_duplicate.count(i) > 1:
    list_duplicate.remove(i)

print(list_duplicate)

[100, 20, 0, -30]

In [ ]:
list_duplicate_1 = [1, 2, 4, 5, 7, 3, 2, 4, 1]   #tried on another list

remove_duplicates(list_duplicate_1)

[1, 2, 4, 5, 7, 3]

In [ ]:
# write a function to remove duplicates from a list of numbers   #solutions by Dr Obay

list_duplicate = [100, 20, -30, 100, 20, 0, -30]

def remove_dup(x):
  new_list = []

  for i in x:
    if i not in new_list:
      new_list.append(i)

  return (new_list)

In [ ]:
remove_dup(list_duplicate)

[100, 20, -30, 0]

In [ ]:
list_a = [22, 88, -20, 88, 2.5, 22, 0]

remove_dup(list_a)

[22, 88, -20, 2.5, 0]

In [ ]:
def remove_dupl(list_duplicate):

  counts = {}

  for i in list_duplicate:
   if list_duplicate.count(i) > 1:
      list_duplicate.remove(i)

  print(list_duplicate)

In [ ]:
list111 = [5,5,5,5,1,1,1]

remove_dupl(list111)

[5, 5, 1]

* **Pandas** : Python Data Analysis
* **Numpy** : Numerical Phyton
* **Scipy** : Scientific Phyton
* **Matplotlib** : Plotting library for Phyton (Data Visualization)

In [ ]:
import pandas as pd

''' creating a sample of dataset by using dictionary'''
''' creating a data frame from the dictionary'''
''' keys are the columns and values are the rows'''


mydata = {

        'Name': ['Mohammed', 'Nurual', 'Aziz', 'Fatimah'],
        'Age' : [23, 32, 30, 27],
        'City' : ['Kuala Lumpur', 'Kuantan', 'Shah Alam', 'Selangor'],
        'Salary' : [5000, 7000, 12000, 9000]
}

mydata

{'Name': ['Mohammed', 'Nurual', 'Aziz', 'Fatimah'],
 'Age': [23, 32, 30, 27],
 'City': ['Kuala Lumpur', 'Kuantan', 'Shah Alam', 'Selangor'],
 'Salary': [5000, 7000, 12000, 9000]}

In [ ]:
type(mydata)

dict

In [ ]:
#convert dictionary to data frame      #pandas always read as data frame

df = pd.DataFrame(mydata)

df.head()

       Name  Age          City  Salary
0  Mohammed   23  Kuala Lumpur    5000
1    Nurual   32       Kuantan    7000
2      Aziz   30     Shah Alam   12000
3   Fatimah   27      Selangor    9000

In [ ]:
data1 = {

         'A': ['A1', 'A2','A3', 'A4'],
         'B': ['B1', 'B2', 'B3', 'B4'],
         'C': ['C1', 'C2', 'C3', 'C4'],
         'D': ['D1', 'D2', 'D3', 'D4']
}

data2 = {

         'A': ['A5', 'A6', 'A7', 'A8'],
         'B': ['B5', 'B6', 'B7', 'B8'],
         'C': ['C5', 'C6', 'C7', 'C8'],
         'D': ['D5', 'D6', 'D7', 'D8']
}

df_data1 = pd.DataFrame(data1)

df_data2 = pd.DataFrame(data2)

In [ ]:
df_data1.head()

    A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4

In [ ]:
df_data2.head()

    A   B   C   D
0  A5  B5  C5  D5
1  A6  B6  C6  D6
2  A7  B7  C7  D7
3  A8  B8  C8  D8

In [ ]:
df_data1_data2 =[df_data1, df_data2]  #jadikan dua dua list dulu

df_1_2 = pd.concat(df_data1_data2)   #ni combine dua dua. dia just put both data beside each other

df_1_2.head(8)    #hasil dia index dia follow yang lama.

    A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4
0  A5  B5  C5  D5
1  A6  B6  C6  D6
2  A7  B7  C7  D7
3  A8  B8  C8  D8

In [ ]:
#index resetting

df_1_2 = df_1_2.reset_index(drop=True)   #changing the parameter. change the default value. reset tu act as 'False'

In [ ]:
df_1_2.head(8)

    A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4
4  A5  B5  C5  D5
5  A6  B6  C6  D6
6  A7  B7  C7  D7
7  A8  B8  C8  D8

In [ ]:
data3 = {                           #concatenate data rows dengan column kena ada jumlah yang sama

         'E': ['E1', 'E2', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8'],
         'F': ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8'],
}

df_data3 = pd.DataFrame(data3)

df_data3.head(8)

    E   F
0  E1  F1
1  E2  F2
2  E3  F3
3  E4  F4
4  E5  F5
5  E6  F6
6  E7  F7
7  E8  F8

In [ ]:
df_all = [df_1_2, df_data3]

df_all = pd.concat(df_all, axis=1)    #axis = 1 tu for concatenate columns. tapi kalau row actually axis = 0, cuma tak mention sebab default

df_all.head(8)

    A   B   C   D   E   F
0  A1  B1  C1  D1  E1  F1
1  A2  B2  C2  D2  E2  F2
2  A3  B3  C3  D3  E3  F3
3  A4  B4  C4  D4  E4  F4
4  A5  B5  C5  D5  E5  F5
5  A6  B6  C6  D6  E6  F6
6  A7  B7  C7  D7  E7  F7
7  A8  B8  C8  D8  E8  F8

In [ ]:
df_all.shape    #(num of rows, num of columns)

(8, 6)

In [ ]:
import pandas as pd

df = pd.DataFrame()

dataA = {

         'Name' : ['Sya', 'Syud', 'Naqibah', 'Nazura', 'Abidah', 'Saras', 'Anis', 'Maryam', 'Aishah', 'Nabilah', 'Puteri'],
         'ID' : [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011],
         'Experience': [6, 3, 4, 2, 3, 2, 0, 7, 2, 3, 4,],
         'Month': ['July', 'August', 'October', 'April', 'January', 'May', 'January', 'June', 'July', 'September', 'November']
}

dataB = {

         'Name' : ['Hafiz', 'Farhan', 'Deen', 'Haikal', 'Azri', 'Amirul', 'Ifham', 'Salman', 'Fakhrul', 'Saniy','Rafi'],
         'ID' : [1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024],
         'Experience': [3, 4, 6, 7, 3, 6, 2, 1, 0, 6, 5,],
         'Month': ['January', 'March', 'September', 'July', 'February', 'October', 'July', 'November', 'June', 'August', 'December']
}

df_A = pd.DataFrame(dataA)

df_B = pd.DataFrame(dataB)

In [ ]:
df_A.head()

df_B.head()

     Name    ID  Experience      Month
0   Hafiz  1014           3    January
1  Farhan  1015           4      March
2    Deen  1016           6  September
3  Haikal  1017           7       July
4    Azri  1018           3   February

In [ ]:
df_A_B = [df_A, df_B]

df_AB = pd.concat(df_A_B)

df_AB.head(22)

       Name    ID  Experience      Month
0       Sya  1001           6       July
1      Syud  1002           3     August
2   Naqibah  1003           4    October
3    Nazura  1004           2      April
4    Abidah  1005           3    January
5     Saras  1006           2        May
6      Anis  1007           0    January
7    Maryam  1008           7       June
8    Aishah  1009           2       July
9   Nabilah  1010           3  September
10   Puteri  1011           4   November
0     Hafiz  1014           3    January
1    Farhan  1015           4      March
2      Deen  1016           6  September
3    Haikal  1017           7       July
4      Azri  1018           3   February
5    Amirul  1019           6    October
6     Ifham  1020           2       July
7    Salman  1021           1   November
8   Fakhrul  1022           0       June
9     Saniy  1023           6     August
10     Rafi  1024           5   December

In [ ]:
df_AB = df_AB.reset_index(drop=True)

df_AB.head(22)

       Name    ID  Experience      Month
0       Sya  1001           6       July
1      Syud  1002           3     August
2   Naqibah  1003           4    October
3    Nazura  1004           2      April
4    Abidah  1005           3    January
5     Saras  1006           2        May
6      Anis  1007           0    January
7    Maryam  1008           7       June
8    Aishah  1009           2       July
9   Nabilah  1010           3  September
10   Puteri  1011           4   November
11    Hafiz  1014           3    January
12   Farhan  1015           4      March
13     Deen  1016           6  September
14   Haikal  1017           7       July
15     Azri  1018           3   February
16   Amirul  1019           6    October
17    Ifham  1020           2       July
18   Salman  1021           1   November
19  Fakhrul  1022           0       June
20    Saniy  1023           6     August
21     Rafi  1024           5   December

In [ ]:
dataC = {

         'Name' :['Hikmah','Amy', 'Obay', 'Shafi'],
         'ID' : [1012, 1013, 1025, 1026],
         'Experience': [2, 4, 8, 3],
         'Month': ['August', 'November', 'July', 'January']
}

dataC = pd.DataFrame(dataC)

dataC.head()

     Name    ID  Experience     Month
0  Hikmah  1012           2    August
1     Amy  1013           4  November
2    Obay  1025           8      July
3   Shafi  1026           3   January

In [ ]:
df_ABC = pd.concat([df_AB, dataC])

df_ABC.head(26)

       Name    ID  Experience      Month
0       Sya  1001           6       July
1      Syud  1002           3     August
2   Naqibah  1003           4    October
3    Nazura  1004           2      April
4    Abidah  1005           3    January
5     Saras  1006           2        May
6      Anis  1007           0    January
7    Maryam  1008           7       June
8    Aishah  1009           2       July
9   Nabilah  1010           3  September
10   Puteri  1011           4   November
11    Hafiz  1014           3    January
12   Farhan  1015           4      March
13     Deen  1016           6  September
14   Haikal  1017           7       July
15     Azri  1018           3   February
16   Amirul  1019           6    October
17    Ifham  1020           2       July
18   Salman  1021           1   November
19  Fakhrul  1022           0       June
20    Saniy  1023           6     August
21     Rafi  1024           5   December
0    Hikmah  1012           2     August
1       Amy  1013           4   November
2      Obay  1025           8       July
3     Shafi  1026           3    January

In [ ]:
df_ABC = df_ABC.reset_index(drop=True)

df_ABC.head(26)

       Name    ID  Experience      Month
0       Sya  1001           6       July
1      Syud  1002           3     August
2   Naqibah  1003           4    October
3    Nazura  1004           2      April
4    Abidah  1005           3    January
5     Saras  1006           2        May
6      Anis  1007           0    January
7    Maryam  1008           7       June
8    Aishah  1009           2       July
9   Nabilah  1010           3  September
10   Puteri  1011           4   November
11    Hafiz  1014           3    January
12   Farhan  1015           4      March
13     Deen  1016           6  September
14   Haikal  1017           7       July
15     Azri  1018           3   February
16   Amirul  1019           6    October
17    Ifham  1020           2       July
18   Salman  1021           1   November
19  Fakhrul  1022           0       June
20    Saniy  1023           6     August
21     Rafi  1024           5   December
22   Hikmah  1012           2     August
23      Amy  1013           4   November
24     Obay  1025           8       July
25    Shafi  1026           3    January

In [ ]:
dataADD = {

           'Gender' : ['F', 'F', 'F', 'F', 'F', 'F','F', 'F', 'F', 'F', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'F', 'M', 'M'],
           'Age': [27, 25, 24, 25, 21, 23, 26, 27, 26, 28, 29, 25, 25, 24, 27, 27, 24, 23, 24, 25, 26, 25, 27, 28, 29, 20]
}

dataADD = pd.DataFrame(dataADD)

dataADD.head()

  Gender  Age
0      F   27
1      F   25
2      F   24
3      F   25
4      F   21

In [ ]:
df_ABC_ADD = pd.concat([df_ABC, dataADD], axis=1)

df_ABC_ADD.head(26)

       Name    ID  Experience      Month Gender  Age
0       Sya  1001           6       July      F   27
1      Syud  1002           3     August      F   25
2   Naqibah  1003           4    October      F   24
3    Nazura  1004           2      April      F   25
4    Abidah  1005           3    January      F   21
5     Saras  1006           2        May      F   23
6      Anis  1007           0    January      F   26
7    Maryam  1008           7       June      F   27
8    Aishah  1009           2       July      F   26
9   Nabilah  1010           3  September      F   28
10   Puteri  1011           4   November      F   29
11    Hafiz  1014           3    January      M   25
12   Farhan  1015           4      March      M   25
13     Deen  1016           6  September      M   24
14   Haikal  1017           7       July      M   27
15     Azri  1018           3   February      M   27
16   Amirul  1019           6    October      M   24
17    Ifham  1020           2       July      M   23
18   Salman  1021           1   November      M   24
19  Fakhrul  1022           0       June      M   25
20    Saniy  1023           6     August      M   26
21     Rafi  1024           5   December      M   25
22   Hikmah  1012           2     August      F   27
23      Amy  1013           4   November      F   28
24     Obay  1025           8       July      M   29
25    Shafi  1026           3    January      M   20

In [ ]:
import pandas as pd

df = pd.read_csv('NFLX.csv')

df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-12-16,119.800003,123.000000,118.089996,122.639999,122.639999,13181000
1,2015-12-17,123.970001,126.349998,122.419998,122.510002,122.510002,17284900
2,2015-12-18,120.849998,122.190002,117.919998,118.019997,118.019997,17948100
3,2015-12-21,119.510002,119.589996,115.660004,116.629997,116.629997,11670000
4,2015-12-22,117.300003,117.430000,114.860001,116.239998,116.239998,9689000

In [ ]:
df.sample()    #dia bagi random row to look at

,Date,Open,High,Low,Close,Adj Close,Volume
586,2018-04-17,329.660004,338.619995,323.769989,336.059998,336.059998,33866500

In [ ]:
df.sample(10) #random 10 rows

,Date,Open,High,Low,Close,Adj Close,Volume
116,2016-06-03,100.989998,101.000000,98.529999,99.589996,99.589996,9224000
386,2017-06-29,152.820007,152.820007,148.000000,150.089996,150.089996,7142500
617,2018-05-31,353.799988,355.529999,350.209991,351.600006,351.600006,6921700
379,2017-06-20,153.679993,154.500000,151.399994,152.050003,152.050003,4878700
46,2016-02-24,88.500000,91.760002,86.699997,91.610001,91.610001,15972800
422,2017-08-21,166.910004,168.990005,164.229996,166.759995,166.759995,6480700
184,2016-09-09,99.059998,99.389999,96.500000,96.500000,96.500000,7373300
363,2017-05-26,162.839996,163.050003,161.119995,162.429993,162.429993,4834300
90,2016-04-27,92.180000,92.500000,90.209999,91.040001,91.040001,12218900
568,2018-03-21,316.350006,319.399994,314.510010,316.480011,316.480011,5263900

In [ ]:
df.shape

(1007, 7)

In [ ]:
df.index  #number of index start berapa sampai berapa

RangeIndex(start=0, stop=1007, step=1)

In [ ]:
df.columns  #dia bagi nama column semua
#dtype tu data type. pandas baca string tu label as object.
#int called int latitude. float jadi float latitude.

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [ ]:
df.describe()

#count num of rows, mean is the average value, std is normal distribution
#min value, first second and third quartile, max value

,Open,High,Low,Close,Adj Close,Volume
count,1007.000000,1007.000000,1007.000000,1007.000000,1007.000000,1.007000e+03
mean,226.708094,229.972979,223.105690,226.670159,226.670159,9.730586e+06
std,103.305422,104.851349,101.458611,103.203785,103.203785,6.398967e+06
min,80.570000,84.699997,79.949997,82.790001,82.790001,1.616300e+06
25%,125.779999,127.165001,124.355000,125.514999,125.514999,5.573200e+06
50%,197.850006,199.440002,195.330002,198.000000,198.000000,7.857600e+06
75%,325.529999,330.835006,318.869995,325.220001,325.220001,1.178630e+07
max,421.380005,423.209991,413.079987,418.970001,418.970001,5.841040e+07

In [ ]:
df2 = df.copy()

In [ ]:
df2.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-12-16,119.800003,123.000000,118.089996,122.639999,122.639999,13181000
1,2015-12-17,123.970001,126.349998,122.419998,122.510002,122.510002,17284900
2,2015-12-18,120.849998,122.190002,117.919998,118.019997,118.019997,17948100
3,2015-12-21,119.510002,119.589996,115.660004,116.629997,116.629997,11670000
4,2015-12-22,117.300003,117.430000,114.860001,116.239998,116.239998,9689000

In [ ]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-12-16,119.800003,123.000000,118.089996,122.639999,122.639999,13181000
1,2015-12-17,123.970001,126.349998,122.419998,122.510002,122.510002,17284900
2,2015-12-18,120.849998,122.190002,117.919998,118.019997,118.019997,17948100
3,2015-12-21,119.510002,119.589996,115.660004,116.629997,116.629997,11670000
4,2015-12-22,117.300003,117.430000,114.860001,116.239998,116.239998,9689000

In [ ]:
df['High'].mean()   #bracket 'high' tu sebab nak deal with that column je. sebab df is dealing with the whole data set

229.97297904468715

In [ ]:
df['Low'].std()

101.45861102484218

In [ ]:
df['Close'].max()

418.970001

In [ ]:
df['Close'].min()

82.790001

In [ ]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-12-16,119.800003,123.000000,118.089996,122.639999,122.639999,13181000
1,2015-12-17,123.970001,126.349998,122.419998,122.510002,122.510002,17284900
2,2015-12-18,120.849998,122.190002,117.919998,118.019997,118.019997,17948100
3,2015-12-21,119.510002,119.589996,115.660004,116.629997,116.629997,11670000
4,2015-12-22,117.300003,117.430000,114.860001,116.239998,116.239998,9689000

In [ ]:
#call cells

#df.iloc[[row index], [column INDEX]]

df.iloc[[2],[3]]

          Low
2  117.919998

In [ ]:
df.iloc[0:5,2:4]  #kalau guna index slicing takyah inner square brackets dah

         High         Low
0  123.000000  118.089996
1  126.349998  122.419998
2  122.190002  117.919998
3  119.589996  115.660004
4  117.430000  114.860001

In [ ]:
#df.loc[[row index], [column NAME]]

df.loc[[2],['High']]

         High
2  122.190002

In [ ]:
df3 = df.iloc[:, 0:3]

df3.head()   #call first 3 columns

         Date        Open        High
0  2015-12-16  119.800003  123.000000
1  2015-12-17  123.970001  126.349998
2  2015-12-18  120.849998  122.190002
3  2015-12-21  119.510002  119.589996
4  2015-12-22  117.300003  117.430000

In [ ]:
df.info()  #understanding about the whole data
#numerical data - integer or float
#categorical - string a.k.a object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1007 non-null   object
 1   Open       1007 non-null   float64
 2   High       1007 non-null   float64
 3   Low        1007 non-null   float64
 4   Close      1007 non-null   float64
 5   Adj Close  1007 non-null   float64
 6   Volume     1007 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 55.2+ KB

In [ ]:
df.dtypes   #nak tau data type for each column

Date          object
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume         int64
dtype: object

In [ ]:
df.rename(columns={'High':'Test'}, inplace=True)
# 'True' to let the code take an action. now 'rename' status is 'False'.

df.head()

,Date,Open,Test,Low,Close,Adj Close,Volume
0,2015-12-16,119.800003,123.000000,118.089996,122.639999,122.639999,13181000
1,2015-12-17,123.970001,126.349998,122.419998,122.510002,122.510002,17284900
2,2015-12-18,120.849998,122.190002,117.919998,118.019997,118.019997,17948100
3,2015-12-21,119.510002,119.589996,115.660004,116.629997,116.629997,11670000
4,2015-12-22,117.300003,117.430000,114.860001,116.239998,116.239998,9689000

In [ ]:
df.rename(columns={'Low':'Test'})  #dia tak change sebab dia 'False'. dia act on copy of the data

df.head()

,Date,Open,Test,Low,Close,Adj Close,Volume
0,2015-12-16,119.800003,123.000000,118.089996,122.639999,122.639999,13181000
1,2015-12-17,123.970001,126.349998,122.419998,122.510002,122.510002,17284900
2,2015-12-18,120.849998,122.190002,117.919998,118.019997,118.019997,17948100
3,2015-12-21,119.510002,119.589996,115.660004,116.629997,116.629997,11670000
4,2015-12-22,117.300003,117.430000,114.860001,116.239998,116.239998,9689000

In [ ]:
df_test = df.rename(columns={'Low':'Test'})

#now yang ni kita tak letak 'True' juga buttt kita assign dia as new variable df_test.
#dia tak act on df punya data but df_test

df_test.head()

,Date,Open,Test,Test,Close,Adj Close,Volume
0,2015-12-16,119.800003,123.000000,118.089996,122.639999,122.639999,13181000
1,2015-12-17,123.970001,126.349998,122.419998,122.510002,122.510002,17284900
2,2015-12-18,120.849998,122.190002,117.919998,118.019997,118.019997,17948100
3,2015-12-21,119.510002,119.589996,115.660004,116.629997,116.629997,11670000
4,2015-12-22,117.300003,117.430000,114.860001,116.239998,116.239998,9689000

In [ ]:
import numpy as np   #numpy very good to help on arrays

array1 = np.array([1,2,3,4,5,6,7,8,9])

array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(array1)

numpy.ndarray

*What is the difference berween List and Array?*

In Python, both lists and arrays are used to store collections of elements, but they have some differences in terms of functionality and implementation. Here's a breakdown of the key differences between lists and arrays in Python:

*Data Type:*
Lists: Lists in Python are a built-in data type and are part of the standard library. They can hold elements of different data types and are very flexible.
Arrays: Arrays in Python are not a built-in data type but are provided by external libraries like NumPy. Arrays are more rigid in terms of data types and often store homogeneous elements (elements of the same data type) for optimized computation.

*Functionality:*
Lists: Lists provide various methods and operations for adding, removing, and manipulating elements.
Arrays: Arrays, particularly those from libraries like NumPy, provide extensive mathematical operations and optimizations for numerical computations.

*Memory Efficiency:*
Lists: Lists in Python are less memory efficient compared to arrays because they store additional metadata for each element, such as the type of the element and its reference count.

*In summary, the choice between using lists or arrays depends on your specific needs. If you're dealing with general data storage and manipulation, lists are more suitable. If you're working with numerical data and require optimized computations, arrays from libraries like NumPy offer better performance and functionality.*

In [ ]:
#creating 2D array

array2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#creating 3D array

array3 = np.array([[[1,2,3], [4,5,6], [7,8,9]],
                  [[10,11,12], [13,14,15], [16,17,18]],
                  [[19,20,21], [22,23,24], [25,26,27]]]
                  )

array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
array1.shape

(9,)

In [ ]:
array2.shape

(3, 3)

In [ ]:
array3.shape

(3, 3, 3)

In [ ]:
array1.ndim #number of dimension

1

In [ ]:
array2.ndim

2

In [ ]:
array3.ndim

3

In [ ]:
#using linspace - the range is 200 - 900. you wanted 3 numbers to split to 2 categories 200-550, 550-900.

np.linspace(200, 900, num=3)

array([200., 550., 900.])

In [ ]:
np.linspace(200, 900, num=6) #ni dia pecahkan to 6 numbers. got 5 categories

array([200., 340., 480., 620., 760., 900.])

In [3]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

#create numerical data

col1 = np.random.normal(250, 10, 500)     #random, normally distributed
col2 = np.random.normal(100, 20, 500)
col3 = np.random.normal(750, 5, 500)

#create categorical data

categorical_data = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

col4 = np.random.choice(categorical_data, 500)
col5 = np.random.choice(categorical_data, 500)

#create date data

start_date = datetime(2022, 1, 1)
end_date = datetime(2024, 1, 1)

delta = end_date - start_date

date_list = [start_date + timedelta(days=x) for x in range(delta.days)]

col6 = np.random.choice(date_list, 500)

#combine all the columns

data = np.column_stack((col1, col2, col3, col4, col5, col6))

df = pd.DataFrame(data)

df.head()

            0           1           2  3  4          5
0  268.634565  108.526868  749.379061  G  B 2023-10-01
1  250.861928  112.007076  745.843148  C  J 2023-09-03
2   247.53774   81.395361  749.912687  J  F 2023-12-22
3  253.442324   80.449714  748.999601  A  E 2022-06-06
4  246.794227  100.123977  755.948945  J  A 2022-11-28

In [4]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

#create numerical data

col1 = np.random.normal(250, 10, 500)     #random, normally distributed
col2 = np.random.normal(100, 20, 500)
col3 = np.random.normal(750, 5, 500)

#create categorical data

categorical_data = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

col4 = np.random.choice(categorical_data, 500)
col5 = np.random.choice(categorical_data, 500)

#create date data

start_date = datetime(2022, 1, 1)
end_date = datetime(2024, 1, 1)

delta = end_date - start_date

date_list = [start_date + timedelta(days=x) for x in range(delta.days)]

col6 = np.random.choice(date_list, 500)

#combine all the columns

data = np.column_stack((col1, col2, col3, col4, col5, col6))

df = pd.DataFrame(data, columns = ['Num1', 'Num2', 'Num3', 'Cat1', 'Cat2', 'Date'])   #sini dia add columns tu sebab nak change nama columns instead of index

df.head()

         Num1        Num2        Num3 Cat1 Cat2       Date
0  244.473083  117.634018  748.873164    E    D 2023-06-08
1  253.248474   118.80405  753.330758    I    D 2022-02-03
2  258.512354   79.354437  756.769355    B    C 2023-12-23
3  261.114036   96.753181  738.743526    H    G 2023-08-06
4   253.74949  108.997263  742.317279    D    D 2022-02-24

In [5]:
df.shape

(500, 6)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Num1    500 non-null    object
 1   Num2    500 non-null    object
 2   Num3    500 non-null    object
 3   Cat1    500 non-null    object
 4   Cat2    500 non-null    object
 5   Date    500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 23.6+ KB

In [9]:
df.describe()   #ni dia tak bagi semua sebab type dia object

                                Date
count                            500
mean   2023-01-25 23:28:19.200000256
min              2022-01-01 00:00:00
25%              2022-07-29 18:00:00
50%              2023-02-08 00:00:00
75%              2023-07-23 06:00:00
max              2023-12-30 00:00:00

In [10]:
df.describe(include='all')   #ni dia bagi semua type punya summary including type = object
#ni dia tak bagi la mean, std semua sebab dia object. so ada different features dia bagi - unique, top, freq, etc..

,Num1,Num2,Num3,Cat1,Cat2,Date
count,500.000000,500.000000,500.000000,500,500,500
unique,500.000000,500.000000,500.000000,10,10,NaN
top,244.473083,117.634018,748.873164,F,D,NaN
freq,1.000000,1.000000,1.000000,58,64,NaN
mean,NaN,NaN,NaN,NaN,NaN,2023-01-25 23:28:19.200000256
min,NaN,NaN,NaN,NaN,NaN,2022-01-01 00:00:00
25%,NaN,NaN,NaN,NaN,NaN,2022-07-29 18:00:00
50%,NaN,NaN,NaN,NaN,NaN,2023-02-08 00:00:00
75%,NaN,NaN,NaN,NaN,NaN,2023-07-23 06:00:00
max,NaN,NaN,NaN,NaN,NaN,2023-12-30 00:00:00

In [12]:
df['Num1'] = df['Num1'].astype('float')   #change the data type of Num 1 from object to float

df[['Num2', 'Num3']] = df[['Num2', 'Num3']].astype('float')  #dekat 'Num2', 'Num3' tu ada dua square bracket

df.dtypes

Num1           float64
Num2           float64
Num3           float64
Cat1            object
Cat2            object
Date    datetime64[ns]
dtype: object

In [14]:
df.describe()

             Num1        Num2        Num3                           Date
count  500.000000  500.000000  500.000000                            500
mean   249.654710  100.202865  750.100114  2023-01-25 23:28:19.200000256
min    223.519735   25.213827  733.293577            2022-01-01 00:00:00
25%    242.798542   86.836998  746.837405            2022-07-29 18:00:00
50%    249.370886  100.930298  749.984685            2023-02-08 00:00:00
75%    257.110138  113.906945  753.859795            2023-07-23 06:00:00
max    280.459245  153.147438  762.965148            2023-12-30 00:00:00
std      9.756186   20.294261    5.038348                            NaN

In [15]:
df.describe(include='all')

,Num1,Num2,Num3,Cat1,Cat2,Date
count,500.000000,500.000000,500.000000,500,500,500
unique,NaN,NaN,NaN,10,10,NaN
top,NaN,NaN,NaN,F,D,NaN
freq,NaN,NaN,NaN,58,64,NaN
mean,249.654710,100.202865,750.100114,NaN,NaN,2023-01-25 23:28:19.200000256
min,223.519735,25.213827,733.293577,NaN,NaN,2022-01-01 00:00:00
25%,242.798542,86.836998,746.837405,NaN,NaN,2022-07-29 18:00:00
50%,249.370886,100.930298,749.984685,NaN,NaN,2023-02-08 00:00:00
75%,257.110138,113.906945,753.859795,NaN,NaN,2023-07-23 06:00:00
max,280.459245,153.147438,762.965148,NaN,NaN,2023-12-30 00:00:00
std,9.756186,20.294261,5.038348,NaN,NaN,NaN

In [18]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

#create numerical data

column1 = np.random.normal(800, 15, 750)     #random, normally distributed
column2 = np.random.normal(350, 10, 750)
column3 = np.random.normal(1000, 7, 750)

#create categorical data

category = ['Ali', 'Boon', 'Chong', 'David', 'Evelyn', 'Farid', 'Gary', 'Harold', 'Irvin', 'Jacob']

column4 = np.random.choice(category, 750)
column5 = np.random.choice(category, 750)

#create date data

start_date = datetime(2019, 4, 13)
end_date = datetime(2024, 7, 17)

delta = end_date - start_date

date_list = [start_date + timedelta(days=x) for x in range(delta.days)]

column6 = np.random.choice(date_list, 750)

#combine all the columns

data1 = np.column_stack((column1, column2, column3, column4, column5, column6))

df = pd.DataFrame(data1, columns = ['Num1', 'Num2', 'Num3', 'Name1', 'Name2', 'Date'])

df.head()

         Num1        Num2         Num3  Name1  Name2       Date
0  787.364416  351.580695   996.714767  Chong   Gary 2023-06-04
1  792.147952  353.551784  1013.934524  Irvin  David 2020-11-11
2  827.189658  348.451806   995.014842  David   Boon 2019-11-04
3  794.324812  339.737708  1012.225367  Chong  David 2023-09-13
4   769.83551  345.951194  1003.567339   Boon  Jacob 2020-07-19